runtime: python39
env: flex
entrypoint: gunicorn -b :$PORT run:app

runtime_config:
  operating_system: ubuntu22

manual_scaling:
  instances: 1

resources:
  memory_gb: 0.5
  cpu: 1
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto