runtime: python
env: flex
entrypoint: gunicorn -b :$PORT run:app

runtime_config:
  operating_system: ubuntu22

manual_scaling:
  instances: 1

resources:
  memory_gb: 2
  cpu: 2
  disk_size_gb: 10

handlers:
- url: /.*
  script: auto